apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - service-aliases.yaml
  - k8s-global-dashboards-configmap.yaml
  - k8s-node-dashboards-configmap.yaml
