---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid-cache-pvc
  namespace: squid
  labels:
    app.kubernetes.io/name: squid
    app.kubernetes.io/part-of: devops-cli-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 250Gi
