"""Telemetry, OpenTelemetry tracing, and metrics module for devops-cli."""

from __future__ import annotations

from devops_cli.telemetry.context import (
    extract_traceparent,
    extract_traceparent_from_headers,
    generate_span_id,
    generate_trace_id,
    generate_traceparent,
    inject_traceparent_headers,
)
from devops_cli.telemetry.logfire import (
    AgentTurnHandle,
    LogfireBridge,
    LogfireOTelBridgeProcessor,
    LogfireStatus,
    get_logfire_bridge,
    logfire_agent_turn,
    render_agent_turn_panel,
    render_agent_turn_table,
    reset_logfire_bridge,
)
from devops_cli.telemetry.logging_bridge import (
    TraceCorrelationFilter,
    attach_trace_correlation_filter,
    get_current_trace_correlation,
)
from devops_cli.telemetry.memory_profiler import (
    MemoryAllocationItem,
    MemoryProfiler,
    MemoryProfileReport,
    MemoryProfilerError,
    count_open_sockets,
    profile_custom_callable,
    profile_fastmcp_workload,
    profile_http_pool_workload,
    run_memory_profiler,
)
from devops_cli.telemetry.metrics import (
    GLOBAL_METRICS,
    InMemoryMetricsRegistry,
)
from devops_cli.telemetry.propagation import (
    TraceContext,
    extract_env,
    extract_headers,
    inject_env,
    inject_headers,
    new_trace_context,
    parse_traceparent,
)
from devops_cli.telemetry.tracer import (
    ContextPropagatingThread,
    ContextPropagatingThreadPoolExecutor,
    OTelTelemetryClient,
    SpanWaterfallNode,
    bind_context,
    build_span_waterfall_tree,
    clear_span_buffer,
    get_current_span_context,
    get_recent_spans,
    get_trace_spans,
    get_tracer,
    inject_trace_context,
    record_completed_span,
    record_metric,
    reset_tracer,
    trace_span,
    traced,
)
from devops_cli.telemetry.waterfall import (
    flatten_waterfall_tree,
    normalize_jaeger_spans,
    query_jaeger_trace,
    render_waterfall_bar,
    resolve_trace_spans,
)

__all__ = [
    "GLOBAL_METRICS",
    "AgentTurnHandle",
    "ContextPropagatingThread",
    "ContextPropagatingThreadPoolExecutor",
    "InMemoryMetricsRegistry",
    "LogfireBridge",
    "LogfireOTelBridgeProcessor",
    "LogfireStatus",
    "MemoryAllocationItem",
    "MemoryProfileReport",
    "MemoryProfiler",
    "MemoryProfilerError",
    "OTelTelemetryClient",
    "SpanWaterfallNode",
    "TraceContext",
    "TraceCorrelationFilter",
    "attach_trace_correlation_filter",
    "bind_context",
    "build_span_waterfall_tree",
    "clear_span_buffer",
    "count_open_sockets",
    "extract_env",
    "extract_headers",
    "extract_traceparent",
    "extract_traceparent_from_headers",
    "flatten_waterfall_tree",
    "generate_span_id",
    "generate_trace_id",
    "generate_traceparent",
    "get_current_span_context",
    "get_current_trace_correlation",
    "get_logfire_bridge",
    "get_recent_spans",
    "get_trace_spans",
    "get_tracer",
    "inject_env",
    "inject_headers",
    "inject_trace_context",
    "inject_traceparent_headers",
    "logfire_agent_turn",
    "new_trace_context",
    "normalize_jaeger_spans",
    "parse_traceparent",
    "profile_custom_callable",
    "profile_fastmcp_workload",
    "profile_http_pool_workload",
    "query_jaeger_trace",
    "record_completed_span",
    "record_metric",
    "render_agent_turn_panel",
    "render_agent_turn_table",
    "render_waterfall_bar",
    "reset_logfire_bridge",
    "reset_tracer",
    "resolve_trace_spans",
    "run_memory_profiler",
    "trace_span",
    "traced",
]
