---
apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-ca-cert
  namespace: llm
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: devops-cli-stack
data:
  squid-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDjTCCAnWgAwIBAgIULkaD4MdbotOu24dlBfSFEgmTShwwDQYJKoZIhvcNAQEL
    BQAwVjEnMCUGA1UEAwweRGV2T3BzIENMSSBJbi1DbHVzdGVyIFNxdWlkIENBMRMw
    EQYDVQQKDApEZXZPcHMgQ0xJMRYwFAYDVQQLDA1DYWNoaW5nIFByb3h5MB4XDTI2
    MDkxMDIzMjUyNFoXDTM2MDkwNzIzMjUyNFowVjEnMCUGA1UEAwweRGV2T3BzIENM
    SSBJbi1DbHVzdGVyIFNxdWlkIENBMRMwEQYDVQQKDApEZXZPcHMgQ0xJMRYwFAYD
    VQQLDA1DYWNoaW5nIFByb3h5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAvyQA194ylJHopgMYJzVvtsoFBmGkLvc3oPQK/8M/9SW08ExTqh+7huGKPXEy
    2eyo1nMeMFDyjh/rwkE5u4+DBwmcDAcxSRyaA0BupiIeFTksGUHF5Ut8oFcIyU+k
    fj1KkDVCFi0AefHV6T+q1fRxwKCWwIfxrYn+6/EJEt+KKEvtHQS5uBb/k0XucYnw
    sk/1UryFSphTraOgLNfCc9INBcjv8rXF23yAejIwt8+dQu6WkYsUEIyYHxLsmfcT
    7g1/PvWQ6PEbr+dp11eSb26zcKdj4KPBhZu1sg+TKmqtM+Ua0hCrd9u7c3EXnTtS
    ZWfG1+eKqwZvPMzG9HKvlczUrwIDAQABo1MwUTAdBgNVHQ4EFgQUNcG9y02wP5+n
    N7dAGaSbFkNrSqswHwYDVR0jBBgwFoAUNcG9y02wP5+nN7dAGaSbFkNrSqswDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEARgZsAdDs6H++2ClHZ4ZN
    zjNvdD3r1r1TUHqnG4M2UMXkDTGrwbv4hP5NZBCxbqomIfnhikfpzRhA8tXCPz1w
    jl/zF42ZlO6Yk5zUZKCNU6AVFiWi9Erp0dUvW9Z/X+4cXWIQa4UANqIDzbF3I5OJ
    2IvC+aK4RtX55uWVjnFbM6g5LphP7xQEdZqA/gNovNzkIm//maGn2b+qOEGXQ0oa
    7Aop9DV1+Z8I1CUJq6OuHw0TJ9j77m8ZG2NGNWbflHZ9fjAP3p9GDTkKsyRrrj5l
    6nqhQRqfvovIolFF8aVXJ0gVnv/3EaqQGKNCaF2jAuw+mhIXxZ9kbHOzMpDub0nl
    Hw==
    -----END CERTIFICATE-----
