apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roadmap-service-home
  namespace: devops
  labels:
    app.kubernetes.io/name: roadmap-service
    app.kubernetes.io/part-of: devops-cli-stack
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
