apiVersion: v1
kind: Service
metadata:
  name: roadmap-service
  namespace: devops
  labels:
    app.kubernetes.io/name: roadmap-service
    app.kubernetes.io/part-of: devops-cli-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: roadmap-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
