apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-feature-discovery
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab-system
  source:
    repoURL: https://github.com/dan-petty/devops-cli
    targetRevision: main
    path: k8s/gpu-feature-discovery
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
