apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: 4.5.2
    helm:
      valueFiles:
      - $values/k8s/monitoring/k8s-monitoring-values.yaml
  - repoURL: https://github.com/dan-petty/devops-cli
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - SkipDryRunOnMissingResource=true
