apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://host.minikube.internal:9418/k8s
    targetRevision: HEAD
    path: llm
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
