apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  sources:
  - repoURL: https://open-webui.github.io/helm-charts
    chart: open-webui
    targetRevision: 16.6.0
    helm:
      valueFiles:
      - $values/k8s/llm/values-open-webui.yaml
  - repoURL: https://github.com/dan-petty/devops-cli
    targetRevision: release/v0.2.28
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
