apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  sources:
  - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.175.0
    helm:
      valueFiles:
      - $values/k8s/otel/values.yaml
  - repoURL: https://github.com/dan-petty/devops-cli
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: otel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
