apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-operator-crds
    targetRevision: 32.0.1
    helm:
      valueFiles:
      - $values/k8s/monitoring/prometheus-operator-crds-values.yaml
  - repoURL: https://github.com/dan-petty/devops-cli
    targetRevision: release/v0.2.27
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - ServerSideApply=true
