apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  sources:
  - repoURL: https://qdrant.github.io/qdrant-helm
    chart: qdrant
    targetRevision: 1.19.1
    helm:
      valueFiles:
      - $values/k8s/llm/values-qdrant.yaml
  - repoURL: https://github.com/dan-petty/devops-cli
    targetRevision: release/v0.2.27
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: llm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
