---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: devops-cli-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
