"""Domain model registry for devops-cli.

All Pydantic models for structured data exchange are defined in submodules
and re-exported here for convenient single-import access:

    from devops_cli.models import ArgoCDApp, BranchListing, ChatMessage, ...
"""

from __future__ import annotations

from devops_cli.dry_run import CommandDryRunResult
from devops_cli.models.ai import (
    AnalysisMetadata,
    ChatMessage,
    ExportFeedbackRequest,
    ExportFeedbackResult,
    FileAnalysisMeta,
    FindingSummaryEntry,
    MCPToolInfo,
    ProjectAnalysisMeta,
    RAGChunkResult,
    RAGIndexRequest,
    RAGIndexResult,
    RAGSearchRequest,
    RAGSearchResult,
    ReviewBranchRequest,
    ReviewFindingsRequest,
    ReviewFindingsResult,
    ReviewPathRequest,
    ReviewPRRequest,
    ReviewStatsRequest,
    ReviewStatsResult,
    ScratchpadBuffer,
    ScratchpadEntry,
    TelemetryStatusRequest,
    TelemetryStatusResult,
    TelemetryTestSpanRequest,
    TelemetryTestSpanResult,
    VerifyFindingRequest,
    VerifyFindingResult,
)
from devops_cli.models.argo import ArgoCDApp
from devops_cli.models.benchmark import (
    BenchmarkCategory,
    BenchmarkReport,
    BenchmarkTask,
    ModelBenchmarkSummary,
    PeerGrade,
    TaskResponse,
)
from devops_cli.models.ci import (
    CICheckResult,
    CIRunRequest,
    CIRunResult,
)
from devops_cli.models.config import (
    ConfigOptionSpec,
    ConfigOutputRequest,
    ConfigOutputResult,
    ConfigShowRequest,
    ConfigShowResult,
)
from devops_cli.models.docker import (
    ContainerStatEntry,
    DockerLayerAnalysisRequest,
    DockerLayerAnalysisResult,
    DockerPruneRequest,
    DockerPruneResult,
    DockerStatsRequest,
    DockerStatsResult,
)
from devops_cli.models.git import (
    BranchesListRequest,
    BranchListing,
    RepoEntry,
    ReposListRequest,
    ReposListResult,
    ReposStatusRequest,
    ReposStatusResult,
    ReposSyncRequest,
    ReposSyncResult,
    RepoStatusEntry,
)
from devops_cli.models.github import SSHKeyInfo
from devops_cli.models.grafana import GrafanaAlertRule, GrafanaDashboard, GrafanaDatasource
from devops_cli.models.k8s import (
    K8sBootstrapRequest,
    K8sBootstrapResult,
    K8sClusterStatusRequest,
    K8sClusterStatusResult,
    K8sDeployStackRequest,
    K8sDeployStackResult,
    K8sJaegerInfoRequest,
    K8sJaegerInfoResult,
    K8sPodsRequest,
    K8sPodsResult,
    K8sPolicyValidateRequest,
    K8sPolicyValidateResult,
    K8sTeardownStackRequest,
    K8sTeardownStackResult,
    PodInfo,
    PolicyRuleViolation,
)
from devops_cli.models.prometheus import PrometheusQueryResult, PrometheusSeries
from devops_cli.models.release import (
    ReleasePrepareRequest,
    ReleasePrepareResult,
    ReleaseStatusRequest,
    ReleaseStatusResult,
)
from devops_cli.models.security import (
    NetworkIntelRequest,
    NetworkIntelResult,
    PackageIntelRequest,
    PackageIntelResult,
    SecurityScanRequest,
    SecurityScanResult,
    SSHKeyAuditRequest,
    SSHKeyAuditResult,
    StaticFindingEntry,
    UvAuditRequest,
    UvAuditResult,
)
from devops_cli.models.ssh import ManagedSSHKey
from devops_cli.models.tf import (
    TFApplyRequest,
    TFApplyResult,
    TFLintIssue,
    TFLintRequest,
    TFLintResult,
    TFOutputRequest,
    TFOutputResult,
    TFPlanRequest,
    TFPlanResult,
)
from devops_cli.models.tls import (
    CAGenerationRequest,
    CertGenerationRequest,
    CertificateInfo,
    KubernetesTLSSecretResult,
    TLSEnablementSummary,
)
from devops_cli.models.vulnerability import (
    DependencySpec,
    NetworkReference,
    NetworkReputationRecord,
    VulnerabilityRecord,
)
from devops_cli.models.workspace import (
    WorkspaceCleanRequest,
    WorkspaceCleanResult,
    WorkspaceEntry,
    WorkspaceListRequest,
    WorkspaceListResult,
)

__all__ = [
    "AnalysisMetadata",
    "ArgoCDApp",
    "BenchmarkCategory",
    "BenchmarkReport",
    "BenchmarkTask",
    "BranchListing",
    "BranchesListRequest",
    "CAGenerationRequest",
    "CICheckResult",
    "CIRunRequest",
    "CIRunResult",
    "CertGenerationRequest",
    "CertificateInfo",
    "ChatMessage",
    "CommandDryRunResult",
    "ConfigOptionSpec",
    "ConfigOutputRequest",
    "ConfigOutputResult",
    "ConfigShowRequest",
    "ConfigShowResult",
    "ContainerStatEntry",
    "DependencySpec",
    "DockerLayerAnalysisRequest",
    "DockerLayerAnalysisResult",
    "DockerPruneRequest",
    "DockerPruneResult",
    "DockerStatsRequest",
    "DockerStatsResult",
    "ExportFeedbackRequest",
    "ExportFeedbackResult",
    "FileAnalysisMeta",
    "FindingSummaryEntry",
    "GrafanaAlertRule",
    "GrafanaDashboard",
    "GrafanaDatasource",
    "K8sBootstrapRequest",
    "K8sBootstrapResult",
    "K8sClusterStatusRequest",
    "K8sClusterStatusResult",
    "K8sDeployStackRequest",
    "K8sDeployStackResult",
    "K8sJaegerInfoRequest",
    "K8sJaegerInfoResult",
    "K8sPodsRequest",
    "K8sPodsResult",
    "K8sPolicyValidateRequest",
    "K8sPolicyValidateResult",
    "K8sTeardownStackRequest",
    "K8sTeardownStackResult",
    "KubernetesTLSSecretResult",
    "MCPToolInfo",
    "ManagedSSHKey",
    "ModelBenchmarkSummary",
    "NetworkIntelRequest",
    "NetworkIntelResult",
    "NetworkReference",
    "NetworkReputationRecord",
    "PackageIntelRequest",
    "PackageIntelResult",
    "PeerGrade",
    "PodInfo",
    "PolicyRuleViolation",
    "ProjectAnalysisMeta",
    "PrometheusQueryResult",
    "PrometheusSeries",
    "RAGChunkResult",
    "RAGIndexRequest",
    "RAGIndexResult",
    "RAGSearchRequest",
    "RAGSearchResult",
    "ReleasePrepareRequest",
    "ReleasePrepareResult",
    "ReleaseStatusRequest",
    "ReleaseStatusResult",
    "RepoEntry",
    "RepoStatusEntry",
    "ReposListRequest",
    "ReposListResult",
    "ReposStatusRequest",
    "ReposStatusResult",
    "ReposSyncRequest",
    "ReposSyncResult",
    "ReviewBranchRequest",
    "ReviewFindingsRequest",
    "ReviewFindingsResult",
    "ReviewPRRequest",
    "ReviewPathRequest",
    "ReviewStatsRequest",
    "ReviewStatsResult",
    "SSHKeyAuditRequest",
    "SSHKeyAuditResult",
    "SSHKeyInfo",
    "ScratchpadBuffer",
    "ScratchpadEntry",
    "SecurityScanRequest",
    "SecurityScanResult",
    "StaticFindingEntry",
    "TFApplyRequest",
    "TFApplyResult",
    "TFLintIssue",
    "TFLintRequest",
    "TFLintResult",
    "TFOutputRequest",
    "TFOutputResult",
    "TFPlanRequest",
    "TFPlanResult",
    "TLSEnablementSummary",
    "TaskResponse",
    "TelemetryStatusRequest",
    "TelemetryStatusResult",
    "TelemetryTestSpanRequest",
    "TelemetryTestSpanResult",
    "UvAuditRequest",
    "UvAuditResult",
    "VerifyFindingRequest",
    "VerifyFindingResult",
    "VulnerabilityRecord",
    "WorkspaceCleanRequest",
    "WorkspaceCleanResult",
    "WorkspaceEntry",
    "WorkspaceListRequest",
    "WorkspaceListResult",
]
