"""Environment variable names mapped to config option keys."""

from __future__ import annotations

from devops_cli import config_options as opt

ENV_GITHUB_TOKEN = "DEVOPS_CLI_GITHUB_TOKEN"
ENV_GITHUB_DEFAULT_ORG = "DEVOPS_CLI_GITHUB_DEFAULT_ORG"
ENV_SSH_KEY_DIR = "DEVOPS_CLI_SSH_KEY_DIR"
ENV_SSH_ROTATION_DAYS = "DEVOPS_CLI_SSH_ROTATION_DAYS"
ENV_REPOS_BASE_DIR = "DEVOPS_CLI_REPOS_BASE_DIR"
ENV_WORKSPACE_FILE = "DEVOPS_CLI_WORKSPACE_FILE"
ENV_GRAFANA_URL = "DEVOPS_CLI_GRAFANA_URL"
ENV_GRAFANA_TOKEN = "DEVOPS_CLI_GRAFANA_TOKEN"
ENV_PROMETHEUS_URL = "DEVOPS_CLI_PROMETHEUS_URL"
ENV_ARGOCD_URL = "DEVOPS_CLI_ARGOCD_URL"
ENV_ARGOCD_TOKEN = "DEVOPS_CLI_ARGOCD_TOKEN"
ENV_AI_PROVIDER = "DEVOPS_CLI_AI_PROVIDER"
ENV_AI_MODEL = "DEVOPS_CLI_AI_MODEL"
ENV_AI_OLLAMA_URL = "DEVOPS_CLI_AI_OLLAMA_URL"
ENV_AI_API_BASE_URL = "DEVOPS_CLI_AI_API_BASE_URL"
ENV_AI_API_KEY = "DEVOPS_CLI_AI_API_KEY"

OPTION_TO_ENV_VAR: dict[str, str] = {
    opt.GITHUB_TOKEN: ENV_GITHUB_TOKEN,
    opt.GITHUB_DEFAULT_ORG: ENV_GITHUB_DEFAULT_ORG,
    opt.SSH_KEY_DIR: ENV_SSH_KEY_DIR,
    opt.SSH_ROTATION_DAYS: ENV_SSH_ROTATION_DAYS,
    opt.REPOS_BASE_DIR: ENV_REPOS_BASE_DIR,
    opt.WORKSPACE_FILE: ENV_WORKSPACE_FILE,
    opt.GRAFANA_URL: ENV_GRAFANA_URL,
    opt.GRAFANA_TOKEN: ENV_GRAFANA_TOKEN,
    opt.PROMETHEUS_URL: ENV_PROMETHEUS_URL,
    opt.ARGOCD_URL: ENV_ARGOCD_URL,
    opt.ARGOCD_TOKEN: ENV_ARGOCD_TOKEN,
    opt.AI_PROVIDER: ENV_AI_PROVIDER,
    opt.AI_MODEL: ENV_AI_MODEL,
    opt.AI_OLLAMA_URL: ENV_AI_OLLAMA_URL,
    opt.AI_API_BASE_URL: ENV_AI_API_BASE_URL,
    opt.AI_API_KEY: ENV_AI_API_KEY,
}


def env_var_for_option(option_key: str) -> str | None:
    """Return the mapped environment variable name for a config option key."""
    return OPTION_TO_ENV_VAR.get(option_key)
