"""Standardized domain exception hierarchy for devops-cli."""

from __future__ import annotations

from devops_cli.exceptions.ai import (
    AgentRunError,
    ApprovalRequired,
    CallDeferred,
    ConcurrencyLimitExceeded,
    ConstellationFailoverError,
    ConstellationQuiesceError,
    ConstellationResumeError,
    ContentFilterError,
    ContextBudgetExceededError,
    DocsIngestionError,
    HarnessExecutionError,
    HarnessValidationError,
    IncompleteToolCall,
    LibraryIngestionError,
    LibraryNotFoundError,
    LLMInferenceError,
    ModelAPIError,
    ModelBundleError,
    ModelHTTPError,
    ModelRetry,
    ModelUnavailableError,
    PersonaExecutionError,
    ReviewPoolError,
    RunCancelled,
    SuspendedResponseExpired,
    ToolFailed,
    UnexpectedModelBehavior,
    UsageLimitExceeded,
    UserError,
)
from devops_cli.exceptions.base import DevOpsCLIError
from devops_cli.exceptions.config import ConfigurationError
from devops_cli.exceptions.docker import (
    DockerError,
    DockerSandboxError,
)
from devops_cli.exceptions.git import (
    BranchAlreadyExistsError,
    GitHubOperationError,
    GitOperationError,
    InvalidBranchNameError,
)
from devops_cli.exceptions.k8s import (
    ChaosExecutionError,
    KubernetesContextError,
    KubernetesDeployError,
    KubernetesError,
)
from devops_cli.exceptions.security import (
    KeyringUnavailableError,
    SecretExposureError,
    SecurityError,
    SSRFBlockedError,
)
from devops_cli.exceptions.telemetry import (
    LogfireConfigurationError,
    TelemetryError,
)
from devops_cli.exceptions.tools import (
    ChecksumMismatchError,
    DependencyError,
    SubprocessError,
    ToolDownloadError,
    ToolExecutionError,
)
from devops_cli.exceptions.validation import (
    InvalidURLError,
    InvalidVersionError,
    ValidationError,
)
from devops_cli.exceptions.valkey import (
    ValkeyAuthenticationError,
    ValkeyCommandError,
    ValkeyConnectionError,
    ValkeyError,
    ValkeyTimeoutError,
)
from devops_cli.exceptions.vault import (
    VaultConfigurationError,
    VaultError,
    VaultKeyError,
    VaultOperationError,
)

__all__ = [
    "AgentRunError",
    "ApprovalRequired",
    "BranchAlreadyExistsError",
    "CallDeferred",
    "ChaosExecutionError",
    "ChecksumMismatchError",
    "ConcurrencyLimitExceeded",
    "ConfigurationError",
    "ConstellationFailoverError",
    "ConstellationQuiesceError",
    "ConstellationResumeError",
    "ContentFilterError",
    "ContextBudgetExceededError",
    "DevOpsCLIError",
    "DockerError",
    "DockerSandboxError",
    "DocsIngestionError",
    "GitHubOperationError",
    "GitOperationError",
    "HarnessExecutionError",
    "HarnessValidationError",
    "IncompleteToolCall",
    "InvalidBranchNameError",
    "InvalidURLError",
    "InvalidVersionError",
    "KeyringUnavailableError",
    "KubernetesContextError",
    "KubernetesDeployError",
    "KubernetesError",
    "LibraryIngestionError",
    "LibraryNotFoundError",
    "LLMInferenceError",
    "LogfireConfigurationError",
    "ModelAPIError",
    "ModelBundleError",
    "ModelHTTPError",
    "ModelRetry",
    "ModelUnavailableError",
    "PersonaExecutionError",
    "ReviewPoolError",
    "RunCancelled",
    "SSRFBlockedError",
    "SecretExposureError",
    "SecurityError",
    "SuspendedResponseExpired",
    "TelemetryError",
    "DependencyError",
    "SubprocessError",
    "ToolDownloadError",
    "ToolExecutionError",
    "ToolFailed",
    "UnexpectedModelBehavior",
    "UsageLimitExceeded",
    "UserError",
    "ValidationError",
    "ValkeyAuthenticationError",
    "ValkeyCommandError",
    "ValkeyConnectionError",
    "ValkeyError",
    "ValkeyTimeoutError",
    "VaultConfigurationError",
    "VaultError",
    "VaultKeyError",
    "VaultOperationError",
]
