"""Standardized domain exception hierarchy for devops-cli."""

from __future__ import annotations

from devops_cli.exceptions.ai import (
    AgentRunError,
    ApprovalRequired,
    CallDeferred,
    ConcurrencyLimitExceeded,
    ConstellationFailoverError,
    ConstellationQuiesceError,
    ConstellationResumeError,
    ContentFilterError,
    ContextBudgetExceededError,
    DocsIngestionError,
    HarnessExecutionError,
    HarnessValidationError,
    IncompleteToolCall,
    LibraryIngestionError,
    LibraryNotFoundError,
    LLMInferenceError,
    ModelAPIError,
    ModelBundleError,
    ModelHTTPError,
    ModelRetry,
    ModelUnavailableError,
    PersonaExecutionError,
    ReviewPoolError,
    RunCancelled,
    SuspendedResponseExpired,
    ToolFailed,
    UnexpectedModelBehavior,
    UsageLimitExceeded,
    UserError,
)
from devops_cli.exceptions.argo import ArgoError, ArgoResourceNotFoundError
from devops_cli.exceptions.base import DevOpsCLIError
from devops_cli.exceptions.config import ConfigurationError
from devops_cli.exceptions.docker import (
    CosignError,
    CosignVerificationError,
    DockerDaemonUnavailableError,
    DockerEngineError,
    DockerError,
    DockerSandboxError,
)
from devops_cli.exceptions.docs import DocCompactionError
from devops_cli.exceptions.git import (
    BranchAlreadyExistsError,
    GitHubGraphQLError,
    GitHubOperationError,
    GitHubRateLimitError,
    GitHubWebhookVerificationError,
    GitOperationError,
    InvalidBranchNameError,
)
from devops_cli.exceptions.k8s import (
    ChaosExecutionError,
    GitOpsSyncError,
    KubernetesContextError,
    KubernetesDeployError,
    KubernetesError,
    KubernetesLoggingError,
)
from devops_cli.exceptions.sandbox import (
    SandboxError,
    SandboxNotFoundError,
    SandboxPortAllocationError,
    SandboxValidationError,
)
from devops_cli.exceptions.security import (
    KeyringUnavailableError,
    SecretExposureError,
    SecurityError,
    SSRFBlockedError,
)
from devops_cli.exceptions.telemetry import (
    LogfireConfigurationError,
    TelemetryError,
)
from devops_cli.exceptions.tools import (
    ChecksumMismatchError,
    DependencyError,
    SubprocessError,
    ToolDownloadError,
    ToolExecutionError,
)
from devops_cli.exceptions.validation import (
    InvalidURLError,
    InvalidVersionError,
    ValidationError,
)
from devops_cli.exceptions.valkey import (
    ValkeyAuthenticationError,
    ValkeyCommandError,
    ValkeyConnectionError,
    ValkeyError,
    ValkeyTimeoutError,
)
from devops_cli.exceptions.vault import (
    VaultConfigurationError,
    VaultError,
    VaultKeyError,
    VaultOperationError,
)

__all__ = [
    "AgentRunError",
    "ApprovalRequired",
    "ArgoError",
    "ArgoResourceNotFoundError",
    "BranchAlreadyExistsError",
    "CallDeferred",
    "ChaosExecutionError",
    "ChecksumMismatchError",
    "ConcurrencyLimitExceeded",
    "ConfigurationError",
    "ConstellationFailoverError",
    "ConstellationQuiesceError",
    "ConstellationResumeError",
    "ContentFilterError",
    "ContextBudgetExceededError",
    "CosignError",
    "CosignVerificationError",
    "DevOpsCLIError",
    "DockerDaemonUnavailableError",
    "DockerEngineError",
    "DockerError",
    "DockerSandboxError",
    "DocCompactionError",
    "DocsIngestionError",
    "GitHubGraphQLError",
    "GitHubOperationError",
    "GitHubRateLimitError",
    "GitHubWebhookVerificationError",
    "GitOperationError",
    "GitOpsSyncError",
    "HarnessExecutionError",
    "HarnessValidationError",
    "IncompleteToolCall",
    "InvalidBranchNameError",
    "InvalidURLError",
    "InvalidVersionError",
    "KeyringUnavailableError",
    "KubernetesContextError",
    "KubernetesDeployError",
    "KubernetesError",
    "KubernetesLoggingError",
    "LibraryIngestionError",
    "LibraryNotFoundError",
    "LLMInferenceError",
    "LogfireConfigurationError",
    "ModelAPIError",
    "ModelBundleError",
    "ModelHTTPError",
    "ModelRetry",
    "ModelUnavailableError",
    "PersonaExecutionError",
    "ReviewPoolError",
    "RunCancelled",
    "SSRFBlockedError",
    "SandboxError",
    "SandboxNotFoundError",
    "SandboxPortAllocationError",
    "SandboxValidationError",
    "SecretExposureError",
    "SecurityError",
    "SuspendedResponseExpired",
    "TelemetryError",
    "DependencyError",
    "SubprocessError",
    "ToolDownloadError",
    "ToolExecutionError",
    "ToolFailed",
    "UnexpectedModelBehavior",
    "UsageLimitExceeded",
    "UserError",
    "ValidationError",
    "ValkeyAuthenticationError",
    "ValkeyCommandError",
    "ValkeyConnectionError",
    "ValkeyError",
    "ValkeyTimeoutError",
    "VaultConfigurationError",
    "VaultError",
    "VaultKeyError",
    "VaultOperationError",
]
