"""Multi-agent orchestrator, memory management, and structured Pydantic agent models."""

from __future__ import annotations

from typing import Any

from devops_cli.ai.agents.memory import AgentMemory, MemoryEntry
from devops_cli.ai.agents.pipeline import (
    MultiAgentPipeline,
    MultiAgentPipelineResult,
    PipelineStepResult,
)
from devops_cli.ai.agents.pydantic_agent import (
    MCP,
    AgentHooks,
    AgentResponse,
    AgentRetries,
    AgentSpec,
    AgentStepNode,
    AgentTool,
    AgentUsage,
    BaseCapability,
    Capability,
    CodeExecutionTool,
    DeferredToolRequests,
    DeferredToolResults,
    FunctionToolset,
    HandleDeferredToolCalls,
    MCPServerTool,
    NativeTool,
    PydanticAgent,
    RunContext,
    TemplateStr,
    Thinking,
    ThinkingPart,
    Tool,
    ToolApproved,
    ToolCall,
    ToolCallPart,
    ToolDenied,
    ToolReturn,
    WebFetch,
    WebFetchTool,
    WebSearch,
    WebSearchTool,
    WebSearchUserLocation,
)
from devops_cli.ai.common_tools import (
    duckduckgo_search_tool,
    tavily_search_tool,
    web_fetch_tool,
)
from devops_cli.ai.ext_langchain import (
    LangChainToolset,
    tool_from_langchain,
)


def __getattr__(name: str) -> Any:
    if name in {
        "Advisor",
        "AgentOverride",
        "ClampOversizedMessages",
        "ClearToolResults",
        "CodeMode",
        "Coder",
        "CompactionReceipt",
        "ContextUsage",
        "DEFAULT_MACROSCOPE_GUIDANCE",
        "DEFAULT_PLANNING_GUIDANCE",
        "DEFAULT_PLAYWRIGHT_GUIDANCE",
        "DEFAULT_RESEARCHER_INSTRUCTIONS",
        "DeduplicateFileReads",
        "DynamicWorkflow",
        "FallbackCompaction",
        "FileSystem",
        "InMemoryPlanStore",
        "LLM_API_KEY_ENV_PATTERNS",
        "MINIMUM_EFFORT_FLOOR",
        "Macroscope",
        "MacroscopeIssue",
        "MacroscopeReview",
        "ModelOption",
        "MountDir",
        "OSAccess",
        "PlanEvent",
        "PlanEventEmitter",
        "PlanItem",
        "Planning",
        "PlanStore",
        "PlaywrightBrowser",
        "RepoContext",
        "ReportContextUsage",
        "Researcher",
        "Shell",
        "SlidingWindowCompaction",
        "SqlitePlanStore",
        "SubAgent",
        "SubAgents",
        "SummarizingCompaction",
        "TieredCompaction",
        "ToolOutputLimits",
        "ToolSearch",
        "TranscriptHandleProvider",
        "WarnNearLimits",
        "WorkflowAgent",
        "clamp_effort",
        "coder_agent",
        "compact_now",
        "is_pinned",
        "pin",
        "reinject_pinned",
        "researcher_agent",
    }:
        import devops_cli.ai.harness

        return getattr(devops_cli.ai.harness, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "Advisor",
    "AgentHooks",
    "AgentMemory",
    "AgentOverride",
    "AgentResponse",
    "AgentRetries",
    "AgentSpec",
    "AgentStepNode",
    "AgentTool",
    "AgentUsage",
    "BaseCapability",
    "Capability",
    "ClampOversizedMessages",
    "ClearToolResults",
    "CodeExecutionTool",
    "CodeMode",
    "Coder",
    "CompactionReceipt",
    "ContextUsage",
    "DEFAULT_MACROSCOPE_GUIDANCE",
    "DEFAULT_PLANNING_GUIDANCE",
    "DEFAULT_PLAYWRIGHT_GUIDANCE",
    "DEFAULT_RESEARCHER_INSTRUCTIONS",
    "DeduplicateFileReads",
    "DeferredToolRequests",
    "DeferredToolResults",
    "DynamicWorkflow",
    "FallbackCompaction",
    "FileSystem",
    "FunctionToolset",
    "HandleDeferredToolCalls",
    "InMemoryPlanStore",
    "LLM_API_KEY_ENV_PATTERNS",
    "LangChainToolset",
    "MCP",
    "MCPServerTool",
    "MINIMUM_EFFORT_FLOOR",
    "Macroscope",
    "MacroscopeIssue",
    "MacroscopeReview",
    "MemoryEntry",
    "ModelOption",
    "MountDir",
    "MultiAgentPipeline",
    "MultiAgentPipelineResult",
    "NativeTool",
    "OSAccess",
    "PipelineStepResult",
    "PlanEvent",
    "PlanEventEmitter",
    "PlanItem",
    "Planning",
    "PlanStore",
    "PlaywrightBrowser",
    "PydanticAgent",
    "RepoContext",
    "ReportContextUsage",
    "Researcher",
    "RunContext",
    "Shell",
    "SlidingWindowCompaction",
    "SubAgent",
    "SubAgents",
    "SummarizingCompaction",
    "SqlitePlanStore",
    "TemplateStr",
    "Thinking",
    "ThinkingPart",
    "TieredCompaction",
    "Tool",
    "ToolApproved",
    "ToolCall",
    "ToolCallPart",
    "ToolDenied",
    "ToolOutputLimits",
    "ToolReturn",
    "ToolSearch",
    "TranscriptHandleProvider",
    "WarnNearLimits",
    "WebFetch",
    "WebFetchTool",
    "WebSearch",
    "WebSearchTool",
    "WebSearchUserLocation",
    "WorkflowAgent",
    "clamp_effort",
    "coder_agent",
    "compact_now",
    "duckduckgo_search_tool",
    "is_pinned",
    "pin",
    "reinject_pinned",
    "researcher_agent",
    "tavily_search_tool",
    "tool_from_langchain",
    "web_fetch_tool",
]
