"""Pydantic Agent facade re-exporting all submodules for backward-compatibility."""

from __future__ import annotations

from devops_cli.ai.agents.agent import PydanticAgent
from devops_cli.ai.agents.capabilities import (
    MCP,
    BaseCapability,
    Capability,
    CodeExecutionTool,
    DeferredToolRequests,
    DeferredToolResults,
    HandleDeferredToolCalls,
    Instrumentation,
    MCPServerTool,
    NativeTool,
    SystemReminders,
    Thinking,
    ThinkingPart,
    ToolApproved,
    ToolCallPart,
    ToolDenied,
    WebFetch,
    WebFetchTool,
    WebSearch,
    WebSearchTool,
    WebSearchUserLocation,
)
from devops_cli.ai.agents.context import (
    AgentHooks,
    AgentRetries,
    AgentStepNode,
    AgentUsage,
    RunContext,
    _check_path_traversal,
)
from devops_cli.ai.agents.models import AgentResponse
from devops_cli.ai.agents.runner import (
    _create_deferred_tool_request,
    _create_tool_retry_message,
    _detect_tool_intent,
    _execute_single_tool,
    _find_deferred_tool_handler,
    _handle_deferred_resolution,
    _is_scratchpad_deliberation,
    _record_and_broadcast_thoughts,
    _resolve_fallback_output,
    _resolve_thinking_preference,
    _validate_agent_output,
)
from devops_cli.ai.agents.tools import (
    AgentSpec,
    AgentTool,
    FunctionToolset,
    TemplateStr,
    Tool,
    ToolCall,
    ToolReturn,
)

__all__ = [
    "AgentHooks",
    "AgentResponse",
    "AgentRetries",
    "AgentSpec",
    "AgentStepNode",
    "AgentTool",
    "AgentUsage",
    "BaseCapability",
    "Capability",
    "CodeExecutionTool",
    "DeferredToolRequests",
    "DeferredToolResults",
    "FunctionToolset",
    "HandleDeferredToolCalls",
    "Instrumentation",
    "MCP",
    "MCPServerTool",
    "NativeTool",
    "PydanticAgent",
    "RunContext",
    "SystemReminders",
    "TemplateStr",
    "Thinking",
    "ThinkingPart",
    "Tool",
    "ToolApproved",
    "ToolCall",
    "ToolCallPart",
    "ToolDenied",
    "ToolReturn",
    "WebFetch",
    "WebFetchTool",
    "WebSearch",
    "WebSearchTool",
    "WebSearchUserLocation",
    "_check_path_traversal",
    "_create_deferred_tool_request",
    "_create_tool_retry_message",
    "_detect_tool_intent",
    "_execute_single_tool",
    "_find_deferred_tool_handler",
    "_handle_deferred_resolution",
    "_is_scratchpad_deliberation",
    "_record_and_broadcast_thoughts",
    "_resolve_fallback_output",
    "_resolve_thinking_preference",
    "_validate_agent_output",
]
