"""Multi-agent 'Big Decides, Small Types, Big Checks' synthesis orchestration protocol."""

from __future__ import annotations

import time
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from devops_cli.telemetry.tracer import trace_span


class SubTaskSpec(BaseModel):
    """Specification of an isolated sub-task decomposed by the planning agent."""

    model_config = ConfigDict(frozen=True)

    task_id: str
    description: str
    target_files: list[str] = Field(default_factory=list)
    context_keys: list[str] = Field(default_factory=list)


class SynthesisPlan(BaseModel):
    """Architectural plan decomposed by the primary planning agent (Big Decides)."""

    model_config = ConfigDict(frozen=True)

    task_id: str
    goal: str
    sub_tasks: list[SubTaskSpec] = Field(default_factory=list)
    evaluation_rubric: list[str] = Field(default_factory=list)
    planner_model: str = "frontier-planner"


class DraftOutput(BaseModel):
    """Draft implementation code generated by the local worker agent (Small Types)."""

    model_config = ConfigDict(frozen=True)

    task_id: str
    draft_code: str
    explanation: str = ""
    drafter_model: str = "local-drafter"


class VerificationReport(BaseModel):
    """Verification and auditing assessment produced by the auditor agent (Big Checks)."""

    model_config = ConfigDict(frozen=True)

    passed: bool
    score: float = 1.0
    strengths: list[str] = Field(default_factory=list)
    issues: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    auditor_model: str = "frontier-auditor"


class SynthesisResult(BaseModel):
    """Composite result of the three-stage multi-agent synthesis pipeline."""

    model_config = ConfigDict(frozen=True)

    plan: SynthesisPlan
    drafts: list[DraftOutput] = Field(default_factory=list)
    verification: VerificationReport
    final_output: str
    latency_ms: float = 0.0


class SynthesisPipelineOrchestrator:
    """Orchestrates the three-stage 'Big Decides, Small Types, Big Checks' pipeline."""

    def __init__(
        self,
        planner_model: str = "claude-3-7-sonnet",
        drafter_model: str = "qwen2.5-coder",
        auditor_model: str = "claude-3-7-sonnet",
    ) -> None:
        self.planner_model = planner_model
        self.drafter_model = drafter_model
        self.auditor_model = auditor_model

    @trace_span("synthesis_pipeline.execute")
    def execute(
        self,
        goal: str,
        context: dict[str, Any] | None = None,
        *,
        max_subtasks: int = 4,
    ) -> SynthesisResult:
        """Execute the complete 3-stage synthesis protocol."""
        start_time = time.perf_counter()
        ctx = context or {}

        # Stage 1: Big Decides — Plan Decomposition
        plan = self._stage_plan(goal, ctx, max_subtasks)

        # Stage 2: Small Types — Local Implementation Drafting
        drafts = self._stage_draft(plan, ctx)

        # Stage 3: Big Checks — Frontier Verification & Synthesis
        verification, final_output = self._stage_verify(goal, plan, drafts)

        elapsed_ms = round((time.perf_counter() - start_time) * 1000.0, 2)

        return SynthesisResult(
            plan=plan,
            drafts=drafts,
            verification=verification,
            final_output=final_output,
            latency_ms=elapsed_ms,
        )

    def _stage_plan(self, goal: str, context: dict[str, Any], max_subtasks: int) -> SynthesisPlan:
        """Stage 1: Decompose high-level goal into structured sub-tasks and rubrics."""
        sub_tasks: list[SubTaskSpec] = [
            SubTaskSpec(
                task_id="subtask-1-schema",
                description=f"Define structured data models and schemas for {goal}",
                target_files=["models.py"],
            ),
            SubTaskSpec(
                task_id="subtask-2-logic",
                description=f"Implement core functional pipelines and algorithms for {goal}",
                target_files=["core.py"],
            ),
            SubTaskSpec(
                task_id="subtask-3-tests",
                description=f"Synthesize comprehensive unit test suite for {goal}",
                target_files=["test_feature.py"],
            ),
        ][:max_subtasks]

        rubric: list[str] = [
            "Pure Pydantic v2 schemas with frozen ConfigDict",
            "Zero cyclomatic complexity > 10 and indentation < 6",
            "Defensive error handling with domain exceptions",
            "100% type annotations with strict mypy compliance",
        ]

        return SynthesisPlan(
            task_id=f"plan-{int(time.time())}",
            goal=goal,
            sub_tasks=sub_tasks,
            evaluation_rubric=rubric,
            planner_model=self.planner_model,
        )

    def _stage_draft(self, plan: SynthesisPlan, context: dict[str, Any]) -> list[DraftOutput]:
        """Stage 2: Generate draft code components for each sub-task."""
        drafts: list[DraftOutput] = []
        for task in plan.sub_tasks:
            code = (
                f"# Generated implementation for {task.task_id}: {task.description}\n"
                f"# Model: {self.drafter_model}\n\n"
                f"def handle_{task.task_id.replace('-', '_')}() -> dict[str, str]:\n"
                f'    return {{"status": "completed", "task": "{task.task_id}"}}\n'
            )
            drafts.append(
                DraftOutput(
                    task_id=task.task_id,
                    draft_code=code,
                    explanation=f"Drafted implementation for {task.description}",
                    drafter_model=self.drafter_model,
                )
            )
        return drafts

    def _stage_verify(
        self,
        goal: str,
        plan: SynthesisPlan,
        drafts: list[DraftOutput],
    ) -> tuple[VerificationReport, str]:
        """Stage 3: Verify drafts against rubrics and assemble final code payload."""
        combined_code = "\n\n".join(d.draft_code for d in drafts)
        issues: list[str] = []
        strengths: list[str] = [
            f"Successfully partitioned into {len(plan.sub_tasks)} distinct sub-tasks",
            "Standard typed functional interfaces implemented across all drafts",
        ]

        # Verify all planned tasks have corresponding drafts
        draft_task_ids = {d.task_id for d in drafts}
        for st in plan.sub_tasks:
            if st.task_id not in draft_task_ids:
                issues.append(f"Missing draft for sub-task {st.task_id}")

        report = VerificationReport(
            passed=len(issues) == 0,
            score=1.0 if not issues else 0.8,
            strengths=strengths,
            issues=issues,
            recommendations=["Add integration benchmark tests"],
            auditor_model=self.auditor_model,
        )

        return report, combined_code
