"""AI client, persona utilities, response formatting, and reasoning streaming engine."""

from __future__ import annotations

from typing import Any


def __getattr__(name: str) -> Any:
    try:
        import importlib

        return importlib.import_module(f"devops_cli.ai.{name}")
    except ModuleNotFoundError:
        pass

    if name in {"AIClientError", "LLMClient", "LLMResponse", "model_request_sync", "model_request"}:
        import devops_cli.ai.client

        return getattr(devops_cli.ai.client, name)
    if name in {
        "StreamedResponseSync",
        "direct_model_request",
        "direct_model_request_stream",
        "direct_model_request_stream_sync",
        "direct_model_request_sync",
        "extract_response_text",
        "extract_response_thinking",
        "model_request_stream",
        "model_request_stream_sync",
        "to_llm_response",
        "to_model_messages",
    }:
        import devops_cli.ai.direct

        return getattr(devops_cli.ai.direct, name)
    if name in {
        "BaseDurabilityCapability",
        "LocalDurabilityCapability",
        "create_durable_pydantic_agent",
        "get_available_durable_engines",
        "is_dbos_available",
        "is_prefect_available",
        "is_temporal_available",
        "resolve_durability_capability",
    }:
        import devops_cli.ai.durable

        return getattr(devops_cli.ai.durable, name)
    if name in {
        "AgentRunError",
        "ApprovalRequired",
        "CallDeferred",
        "ConcurrencyLimitExceeded",
        "ContentFilterError",
        "ContextBudgetExceededError",
        "CostCalculationFailedWarning",
        "CostNotFoundWarning",
        "FallbackExceptionGroup",
        "IncompleteToolCall",
        "LLMInferenceError",
        "MessageHistoryMutatedWarning",
        "ModelAPIError",
        "ModelHTTPError",
        "ModelRetry",
        "ModelUnavailableError",
        "PersonaExecutionError",
        "PydanticAIDeprecationWarning",
        "RunCancelled",
        "SkipModelRequest",
        "SkipToolExecution",
        "SkipToolValidation",
        "SuspendedResponseExpired",
        "ToolFailed",
        "ToolFailedError",
        "ToolRetryError",
        "UndrainedPendingMessagesError",
        "UnexpectedModelBehavior",
        "UsageLimitExceeded",
        "UserError",
        "extract_cancellation_state",
        "extract_retry_after",
        "format_pydantic_ai_error",
        "is_pydantic_ai_exception",
        "normalize_to_pydantic_ai_error",
    }:
        import devops_cli.ai.exceptions

        return getattr(devops_cli.ai.exceptions, name)
    if name in {
        "CONST_CLAUDE_MD_FILENAME",
        "CONST_COPILOT_INSTRUCTIONS_PATH",
        "DEFAULT_AGENT_FILES",
        "ProjectMetadata",
        "generate_agents_md",
        "generate_instruction_content",
        "generate_pointer_stub",
        "parse_project_metadata",
        "scaffold_agent_instructions",
    }:
        import devops_cli.ai.instruction_generator

        return getattr(devops_cli.ai.instruction_generator, name)
    if name in {
        "KnowledgeBaseStats",
        "get_knowledge_base_dir",
        "get_knowledge_base_stats",
        "list_knowledge_base_articles",
        "load_kb_article",
    }:
        import devops_cli.ai.kb

        return getattr(devops_cli.ai.kb, name)
    if name in {"ModelBundleManifest", "bundle_ollama_models"}:
        import devops_cli.ai.model_bundler

        return getattr(devops_cli.ai.model_bundler, name)
    if name in {
        "CachedLLMResponse",
        "LLMResponseCache",
        "ResponseCacheStats",
        "get_llm_response_cache",
        "reset_llm_response_cache",
    }:
        import devops_cli.ai.response_cache

        return getattr(devops_cli.ai.response_cache, name)
    if name in {
        "ExtractedToolCall",
        "FormattedLLMResponse",
        "extract_tool_invocations",
        "fix_llm_response",
        "repair_json_string",
    }:
        import devops_cli.ai.response_repair

        return getattr(devops_cli.ai.response_repair, name)
    if name in {
        "ThinkingStreamProcessor",
        "extract_think_blocks",
        "strip_think_blocks",
    }:
        import devops_cli.ai.thinking_stream

        return getattr(devops_cli.ai.thinking_stream, name)
    if name in {
        "DuckDuckGoResult",
        "DuckDuckGoSearchTool",
        "ExaAnswerResult",
        "ExaAnswerTool",
        "ExaContentResult",
        "ExaFindSimilarTool",
        "ExaGetContentsTool",
        "ExaSearchResult",
        "ExaSearchTool",
        "ExaToolset",
        "ImageGenerationFallbackModel",
        "ImageGenerationFallbackModelFunc",
        "ImageGenerationSubagentTool",
        "ImageGenerationTool",
        "TavilySearchResult",
        "TavilySearchTool",
        "WebFetchLocalTool",
        "WebFetchResult",
        "XSearchFallbackModel",
        "XSearchFallbackModelFunc",
        "XSearchSubagentTool",
        "XSearchTool",
        "duckduckgo_search_tool",
        "exa_answer_tool",
        "exa_find_similar_tool",
        "exa_get_contents_tool",
        "exa_search_tool",
        "image_generation_tool",
        "tavily_search_tool",
        "web_fetch_tool",
        "x_search_tool",
    }:
        import devops_cli.ai.common_tools

        return getattr(devops_cli.ai.common_tools, name)

    if name in {
        "AbstractConcurrencyLimiter",
        "AnyConcurrencyLimit",
        "ConcurrencyLimit",
        "ConcurrencyLimitExceeded",
        "ConcurrencyLimitedModel",
        "ConcurrencyLimiter",
        "get_concurrency_context",
        "get_model_concurrency_limiter",
        "get_shared_concurrency_limiter",
        "limit_model_concurrency",
        "normalize_to_limiter",
        "track_concurrency_slot",
    }:
        import devops_cli.ai.concurrency

        return getattr(devops_cli.ai.concurrency, name)
    if name in {"tool_from_langchain", "LangChainToolset"}:
        import devops_cli.ai.ext_langchain

        return getattr(devops_cli.ai.ext_langchain, name)
    if name in {
        "Advisor",
        "AgentContextInventory",
        "AgentOverride",
        "AssetRoot",
        "Band",
        "CacheBustWarning",
        "CacheMark",
        "ClampOversizedMessages",
        "ClearToolResults",
        "CodeMode",
        "Coder",
        "CompactionReceipt",
        "ContextUsage",
        "ConversationSearch",
        "ConversationSearchMatch",
        "DEFAULT_MACROSCOPE_GUIDANCE",
        "DEFAULT_PLANNING_GUIDANCE",
        "DEFAULT_PLAYWRIGHT_GUIDANCE",
        "DEFAULT_RESEARCHER_INSTRUCTIONS",
        "DeduplicateFileReads",
        "DynamicWorkflow",
        "FallbackCompaction",
        "FileSystem",
        "FileStore",
        "HarnessDeprecationWarning",
        "HistorySource",
        "InMemoryPlanStore",
        "InMemoryStore",
        "LLM_API_KEY_ENV_PATTERNS",
        "LocalFileStore",
        "MINIMUM_EFFORT_FLOOR",
        "Macroscope",
        "MacroscopeIssue",
        "MacroscopeReview",
        "Memory",
        "MemoryFile",
        "MemoryMutationResult",
        "MemoryOperationConflictError",
        "MemorySearchResult",
        "MemoryStore",
        "ModelOption",
        "MountDir",
        "OSAccess",
        "OverflowStore",
        "Passthrough",
        "DEFAULT_PYAI_DOCS_TOPICS",
        "PlanEvent",
        "PlanEventEmitter",
        "PlanItem",
        "Planning",
        "PlanStore",
        "PlaywrightBrowser",
        "PydanticAIDocs",
        "PyaiDocs",
        "RepoContext",
        "ReportContextUsage",
        "Researcher",
        "RunRecord",
        "SearchableMemoryStore",
        "Shell",
        "Skills",
        "ParsedSkill",
        "SlidingWindowCompaction",
        "SnapshotHistorySource",
        "Spill",
        "SqliteMemoryStore",
        "SqlitePlanStore",
        "SubAgent",
        "SubAgents",
        "Summarize",
        "SummarizingCompaction",
        "TieredCompaction",
        "ToolOutputLimits",
        "ToolSearch",
        "TranscriptHandleProvider",
        "Truncate",
        "TruncationStrategy",
        "WarnNearLimits",
        "WarnOnCacheBusts",
        "WorkflowAgent",
        "clamp_effort",
        "coder_agent",
        "compact_now",
        "indented_json",
        "is_pinned",
        "json_lines",
        "pin",
        "reinject_pinned",
        "researcher_agent",
    }:
        import devops_cli.ai.harness

        return getattr(devops_cli.ai.harness, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "AIClientError",
    "AbstractConcurrencyLimiter",
    "Advisor",
    "AgentContextInventory",
    "AgentOverride",
    "AnyConcurrencyLimit",
    "AssetRoot",
    "Band",
    "CacheBustWarning",
    "CacheMark",
    "CachedLLMResponse",
    "ClampOversizedMessages",
    "ClearToolResults",
    "CodeMode",
    "Coder",
    "CompactionReceipt",
    "ConcurrencyLimit",
    "ConcurrencyLimitExceeded",
    "ConcurrencyLimitedModel",
    "ConcurrencyLimiter",
    "CONST_CLAUDE_MD_FILENAME",
    "CONST_COPILOT_INSTRUCTIONS_PATH",
    "ContextUsage",
    "ConversationSearch",
    "ConversationSearchMatch",
    "HarnessDeprecationWarning",
    "HistorySource",
    "DEFAULT_AGENT_FILES",
    "DEFAULT_MACROSCOPE_GUIDANCE",
    "DEFAULT_PLANNING_GUIDANCE",
    "DEFAULT_PLAYWRIGHT_GUIDANCE",
    "DEFAULT_RESEARCHER_INSTRUCTIONS",
    "DeduplicateFileReads",
    "DuckDuckGoResult",
    "DuckDuckGoSearchTool",
    "DynamicWorkflow",
    "ExaAnswerResult",
    "ExaAnswerTool",
    "ExaContentResult",
    "ExaFindSimilarTool",
    "ExaGetContentsTool",
    "ExaSearchResult",
    "ExaSearchTool",
    "ExaToolset",
    "ExtractedToolCall",
    "FallbackCompaction",
    "FileSystem",
    "FormattedLLMResponse",
    "ImageGenerationFallbackModel",
    "ImageGenerationFallbackModelFunc",
    "ImageGenerationSubagentTool",
    "ImageGenerationTool",
    "InMemoryPlanStore",
    "KnowledgeBaseStats",
    "LLMClient",
    "LLMResponse",
    "LLMResponseCache",
    "LLM_API_KEY_ENV_PATTERNS",
    "LangChainToolset",
    "LocalFileStore",
    "MINIMUM_EFFORT_FLOOR",
    "Macroscope",
    "MacroscopeIssue",
    "MacroscopeReview",
    "Memory",
    "MemoryFile",
    "MemoryMutationResult",
    "MemoryOperationConflictError",
    "MemorySearchResult",
    "MemoryStore",
    "FileStore",
    "InMemoryStore",
    "SqliteMemoryStore",
    "SearchableMemoryStore",
    "ModelBundleManifest",
    "ModelOption",
    "MountDir",
    "OSAccess",
    "OverflowStore",
    "Passthrough",
    "PlanEvent",
    "PlanEventEmitter",
    "PlanItem",
    "Planning",
    "PlanStore",
    "PlaywrightBrowser",
    "ProjectMetadata",
    "PydanticAIDocs",
    "PyaiDocs",
    "DEFAULT_PYAI_DOCS_TOPICS",
    "RepoContext",
    "ReportContextUsage",
    "Researcher",
    "RunRecord",
    "ResponseCacheStats",
    "Shell",
    "Skills",
    "ParsedSkill",
    "SlidingWindowCompaction",
    "SnapshotHistorySource",
    "Spill",
    "SqlitePlanStore",
    "SubAgent",
    "SubAgents",
    "Summarize",
    "SummarizingCompaction",
    "ThinkingStreamProcessor",
    "TavilySearchResult",
    "TavilySearchTool",
    "TieredCompaction",
    "ToolOutputLimits",
    "ToolSearch",
    "TranscriptHandleProvider",
    "Truncate",
    "TruncationStrategy",
    "WarnNearLimits",
    "WarnOnCacheBusts",
    "WebFetchLocalTool",
    "WebFetchResult",
    "WorkflowAgent",
    "XSearchFallbackModel",
    "XSearchFallbackModelFunc",
    "XSearchSubagentTool",
    "XSearchTool",
    "bundle_ollama_models",
    "clamp_effort",
    "coder_agent",
    "compact_now",
    "duckduckgo_search_tool",
    "exa_answer_tool",
    "exa_find_similar_tool",
    "exa_get_contents_tool",
    "exa_search_tool",
    "extract_think_blocks",
    "extract_tool_invocations",
    "fix_llm_response",
    "generate_agents_md",
    "generate_instruction_content",
    "generate_pointer_stub",
    "get_concurrency_context",
    "get_knowledge_base_dir",
    "get_knowledge_base_stats",
    "get_llm_response_cache",
    "get_model_concurrency_limiter",
    "get_shared_concurrency_limiter",
    "image_generation_tool",
    "indented_json",
    "is_pinned",
    "json_lines",
    "limit_model_concurrency",
    "list_knowledge_base_articles",
    "load_kb_article",
    "model_request",
    "model_request_stream",
    "model_request_stream_sync",
    "model_request_sync",
    "normalize_to_limiter",
    "parse_project_metadata",
    "pin",
    "reinject_pinned",
    "repair_json_string",
    "researcher_agent",
    "reset_llm_response_cache",
    "scaffold_agent_instructions",
    "StreamedResponseSync",
    "strip_think_blocks",
    "tavily_search_tool",
    "to_llm_response",
    "to_model_messages",
    "tool_from_langchain",
    "track_concurrency_slot",
    "web_fetch_tool",
    "x_search_tool",
    "direct_model_request",
    "direct_model_request_stream",
    "direct_model_request_stream_sync",
    "direct_model_request_sync",
    "extract_response_text",
    "extract_response_thinking",
    "BaseDurabilityCapability",
    "LocalDurabilityCapability",
    "create_durable_pydantic_agent",
    "get_available_durable_engines",
    "is_dbos_available",
    "is_prefect_available",
    "is_temporal_available",
    "resolve_durability_capability",
    "AgentRunError",
    "ApprovalRequired",
    "CallDeferred",
    "ConcurrencyLimitExceeded",
    "ContentFilterError",
    "ContextBudgetExceededError",
    "CostCalculationFailedWarning",
    "CostNotFoundWarning",
    "FallbackExceptionGroup",
    "IncompleteToolCall",
    "LLMInferenceError",
    "MessageHistoryMutatedWarning",
    "ModelAPIError",
    "ModelHTTPError",
    "ModelRetry",
    "ModelUnavailableError",
    "PersonaExecutionError",
    "PydanticAIDeprecationWarning",
    "RunCancelled",
    "SkipModelRequest",
    "SkipToolExecution",
    "SkipToolValidation",
    "SuspendedResponseExpired",
    "ToolFailed",
    "ToolFailedError",
    "ToolRetryError",
    "UndrainedPendingMessagesError",
    "UnexpectedModelBehavior",
    "UsageLimitExceeded",
    "UserError",
    "extract_cancellation_state",
    "extract_retry_after",
    "format_pydantic_ai_error",
    "is_pydantic_ai_exception",
    "normalize_to_pydantic_ai_error",
]
