"""Agent tools submodule for devops-cli."""

from __future__ import annotations

from devops_cli.ai.tools.builtin_tools import (
    argo_apps,
    check_threat_intel,
    docker_analyze_layers,
    git_diff,
    git_status,
    k8s_jaeger_status,
    k8s_pods,
    k8s_validate_manifests,
    list_files,
    rag_search,
    read_file,
    scan_bandit,
    scan_gitleaks,
    scan_iac,
    scan_kubelinter,
    scan_osv,
    scan_pluto,
    scan_popeye,
    scan_semgrep,
    scan_trivy,
    scan_uv_audit,
    search_code,
    tf_lint,
)
from devops_cli.ai.tools.mcp_bridge import get_mcp_agent_tools
from devops_cli.ai.tools.registry import get_default_tools, get_persona_tools

__all__ = [
    "argo_apps",
    "check_threat_intel",
    "docker_analyze_layers",
    "get_default_tools",
    "get_mcp_agent_tools",
    "get_persona_tools",
    "git_diff",
    "git_status",
    "k8s_jaeger_status",
    "k8s_pods",
    "k8s_validate_manifests",
    "list_files",
    "rag_search",
    "read_file",
    "scan_bandit",
    "scan_gitleaks",
    "scan_iac",
    "scan_kubelinter",
    "scan_osv",
    "scan_pluto",
    "scan_popeye",
    "scan_semgrep",
    "scan_trivy",
    "scan_uv_audit",
    "search_code",
    "tf_lint",
]
